name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup
        uses: actions/setup-node@master
        with:
          node-version: "14"

      - name: dependencies
        run: npm ci

      - name: deploy
        run: npx serverless deploy --stage ${{ secrets.SERVERLESS_STAGE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
